server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://35.194.46.162:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log


# scrape_configs:
#   - job_name: docker-logs
#     docker_sd_configs:
#       - host: unix:///var/run/docker.sock
#         refresh_interval: 5s
#     relabel_configs:
#       - source_labels: [__meta_docker_container_label_app]
#         action: keep
#         regex: python_app
#       - source_labels: [__meta_docker_container_name]
#         target_label: container
#       - source_labels: [__meta_docker_container_label_app]
#         target_label: app
#     pipeline_stages:
#       - docker: {}


# scrape_configs:
#   - job_name: python_app_scrape
#     docker_sd_configs:
#       - host: unix:///var/run/docker.sock
#         refresh_interval: 5s
#         # filters:
#         #   - name: name
#         #     values: [python_app]
#     relabel_configs:
#       - source_labels: ['__meta_docker_container_name']
#         regex: '/(.*)'
#         target_label: 'container'
